### PR TITLE
Fixes To Issues

### PR DESCRIPTION
**Pull request by mazlix**
I'd like to just have this PR open until I knock out all the issues so I can link them all up as I go.

### CODE REVIEW

**Comment by tejasmanohar** [comment]
Sure.

**Comment by tejasmanohar** [comment]
Lmk when done here in a comment too

**Comment by tejasmanohar** [comment]
Is this ready to merge. @mazlix ?

**Comment by mazlix** [comment]
Yep! Ready now.

**Comment by tejasmanohar** [comment]
Push to production?

**Comment by mazlix** [comment]
Yeah, I already deployed it.



Justin K

**Comment by tejasmanohar** [comment]
Thanks!

**Pull request merged**
